---
enable_rate_limit_target_namespace: demo-nginx
enable_rate_limit_app_label: demo-nginx
enable_rate_limit_rps: 10
enable_rate_limit_apply_contexts:
  - SIDECAR_INBOUND
enable_rate_limit_envoyfilter_name: demo-rl
